name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    ## Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/s-devops:latest .
    
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/s-devops:latest
