name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    ## Checkout code from repository
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/s-devops:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/s-devops:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH .pem key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem && chmod 600 ~/.ssh/ec2_key.pem

      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ~/.ssh/ec2_key.pem

